name: Bug Report
description: Report a bug
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install the package
        2. Call function X with argument Y
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the relevant environment details.
      multiple: true
      options:
        - Node.js 18
        - Node.js 20
        - Node.js 22
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Windows
        - macOS
        - Linux
    validations:
      required: false

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: The version of the package you are using.
      placeholder: e.g. 2.0.11
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, logs, etc.).
    validations:
      required: false
